---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jdkat
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jdkat
  template:
    metadata:
      labels:
        app: jdkat
    spec:
      containers:
      - name: jdkat
        image: kg0529/flask
        ports:
        - containerPort: 9090